### ISSUE TITLE
News Module

### ISSUE THREAD

**Issue by sadelbrid** [sadelbrid/SmartAlarm#2]

**Comment by drewg2009** [comment]
With there being various News Source(Google, Yahoo!, MSN, etc) the url structures vary quite a bit. Yahoo is super simple to use. The other news sources aren't as straightforward but I will keep looking into a lot more.

**Comment by drewg2009** [comment]
I have managed to get two Spinners working to select the news source and category. Then you click the RSS request button and it feeds the xml or any errors into a ScrollView. Only Yahoo Sports works right now. I plan on doing more research on news sources, url structures, and adding to the url HashMap

**Comment by drewg2009** [comment]
It might not be a terrible idea to think about using a backend service for some of these modules. This way 
setting things like preferred news sources will have dynamic data that will be up to date without having to rerelease a new version of the app. The reason I suggest we think about this is because for instance the "News" module has tons and tons of sources and tons of subcategories of news. It will be a lot of coding with HashMaps just to get this module to seem customizable. Let me know what you think
